export class Client {
  id: string;
  code: string;
  deno: string;
  adresse: string;
  ville: string;
  post: string;
  respon: string;
  tel: string;
  agence: string;
  banque: string;
  telex: string;
  fax: string;
  cadnat: string;
  compte: string;
  edition: string;
  exonor: string;
  duree: string;
  reg: string;
  terme: string;
  marque: string;
  plafond: string;
  zone: string;
  comm: string;
  assujet: string;
  codeTva: string;
  timbre: string;
  ech: string;
  bloc: string;
  datBlc: string;
  typeC: string;
  regle: string;
  lettre: string;
  codeC: string;
  autor: string;
  eMail: string;
  typeComm: string;
  rec: string;
  vend: string;
  represant: string;
  secteur: string;
  objectif: string;
  nature: string;
  datCreat: string;
  mag: string;
  respons2: string;
  adresseusine: string;
  adressesiege: string;
  gsm1: string;
  gsm2: string;
  nouvMag: string;
  ca123: string;
  respons3: string;
  fonction1: string;
  fonction2: string;
  fonction3: string;
  eMail1: string;
  eMail2: string;
  eMail3: string;
  tel2: string;
  tel3: string;
  gsm3: string;
  codGroupe: string;
  modeReg: string;
  plafondEncours: string;
  indic: string;
  bcExige: string;
  constructor() {
    this.id = null ;
    this.code = null ;
    this.deno = null ;
    this.adresse = null ;
    this.ville = null ;
    this.post = null ;
    this.respon = null ;
    this.tel = null ;
    this.agence = null ;
    this.banque = null ;
    this.telex = null ;
    this.fax = null ;
    this.cadnat = null ;
    this.compte = null ;
    this.edition = null ;
    this.exonor = null ;
    this.duree = null ;
    this.reg = null ;
    this.terme = null ;
    this.marque = null ;
    this.plafond = null ;
    this.zone = null ;
    this.comm = null ;
    this.assujet = null ;
    this.codeTva = null ;
    this.timbre = null ;
    this.ech = null ;
    this.bloc = null ;
    this.datBlc = null ;
    this.typeC = null ;
    this.regle = null ;
    this.lettre = null ;
    this.codeC = null ;
    this.autor = null ;
    this.eMail = null ;
    this.typeComm = null ;
    this.rec = null ;
    this.vend = null ;
    this.represant = null ;
    this.secteur = null ;
    this.objectif = null ;
    this.nature = null ;
    this.datCreat = null ;
    this.mag = null ;
    this.respons2 = null ;
    this.adresseusine = null ;
    this.adressesiege = null ;
    this.gsm1 = null ;
    this.gsm2 = null ;
    this.nouvMag = null ;
    this.ca123 = null ;
    this.respons3 = null ;
    this.fonction1 = null ;
    this.fonction2 = null ;
    this.fonction3 = null ;
    this.eMail1 = null ;
    this.eMail2 = null ;
    this.eMail3 = null ;
    this.tel2 = null ;
    this.tel3 = null ;
    this.gsm3 = null ;
    this.codGroupe = null ;
    this.modeReg = null ;
    this.plafondEncours = null ;
    this.indic = null ;
    this.bcExige = null ;
  }
}
