export class DepensesCaissePrincipale {
    id: string;
    code: string;
    libelle: string;
    date: string;
    montant: string;
    mode: string;
    facture: string;
    cheque: string;
    banque: string;
    echeance: string;
    observation: string;
    client: string;
    tire: string;
    sens: string;
    datVer: string;
    datRec: string;
    etat: string;
    etat2: string;
    banqEqm: string;
    borVer: string;
    borEnc: string;
    combine: string;
    regle: string;
    apurement: string;
    dateApur: string;
    borRtr: string;
    numPiece: string;
}
